name: Morning Bullshit

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  gen-bullshit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai
      - name: Generate bullshit
        run: |
          python generate.py --api ${{secrets.GEMINI_API_KEY}} --prompt "${{secrets.PROMPT}}"
      - name: Commit
        run: |
          git config --global user.name ${{secrets.USER_NAME}}
          git config --global user.email ${{secrets.USER_EMAIL}}
          git add -A
          git commit -m "update morning bullshit!"
      - name: Push
        run: |
          git push
